require 'delayed_job'
require 'delayed/shallow_mongoid'
require 'delayed/shallow_mongoid/version'
require 'delayed/shallow_mongoid/mongoid'
require 'delayed/shallow_mongoid/document_stub'
require 'delayed/shallow_mongoid/performable_method'
require 'delayed/shallow_mongoid/performable_mailer'
