require 'delayed_job'
require File.dirname(__FILE__) + '/delayed/shallow_mongoid'
require File.dirname(__FILE__) + '/delayed/shallow_mongoid/document_stub'
require File.dirname(__FILE__) + '/delayed/performable_method'
require File.dirname(__FILE__) + '/delayed/performable_mailer'
